FROM debian:bookworm-slim

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
      avr-libc \
      avrdude \
      avarice \
      binutils-avr \
      ca-certificates \
      gcc-avr \
      gdb-avr \
      git \
      make \
      simavr \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /work

CMD ["bash"]
