#include <avr/io.h>

int main(void)
{
    /* OC0A is PB3 on ATmega1284P. */
    DDRB |= _BV(DDB3);

    /* Fast PWM, non-inverting OC0A, TOP=0xff. */
    TCCR0A = _BV(COM0A1) | _BV(WGM01) | _BV(WGM00);

    /* About 25% duty cycle: (OCR0A + 1) / 256. */
    OCR0A = 63;

    /* Start Timer0 with clk/64. */
    TCCR0B = _BV(CS01) | _BV(CS00);

    for (;;) {
        /* PWM is generated by hardware. */
    }
}
